version: '3.6'

services:

  db:
    container_name: postgres-chat
    image: postgres:16.2
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network

  nginx:
    container_name: nginx-chat
    image: nginx:1.25.4-alpine
    environment:
      TZ: "Europe/Moscow"
    env_file:
      - .env
    volumes:
      - ./backend/code:/var/www/backend
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${WEB_PORT}:80"
    networks:
      - app-network

  app:
    container_name: app-chat
    build:
      context: ./backend/
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend/code:/var/www/backend
    env_file:
      - .env
    networks:
      - app-network


  centrifugo:
    container_name: centrifugo-chat
    image: centrifugo/centrifugo:v5
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - "${CENTRIFUGO_PORT}:8000"
    env_file:
      - .env
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - app-network

  storage:
    container_name: s3-chat
    hostname: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - ./storage/data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge




